/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetCharactersCharacterIdFittingsItem } from './getCharactersCharacterIdFittingsItem';


/**
 * 200 ok object
 */
export interface GetCharactersCharacterIdFittings200Ok { 
    /**
     * description string
     */
    description: string;
    /**
     * fitting_id integer
     */
    fitting_id: number;
    /**
     * items array
     */
    items: Array<GetCharactersCharacterIdFittingsItem>;
    /**
     * name string
     */
    name: string;
    /**
     * ship_type_id integer
     */
    ship_type_id: number;
}

