/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Optional object that is returned if a bookmark was made on a particular item.
 */
export interface GetCorporationsCorporationIdBookmarksItem { 
    /**
     * item_id integer
     */
    item_id: number;
    /**
     * type_id integer
     */
    type_id: number;
}

