/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Summary of victory points gained by the given corporation for the enlisted faction
 */
export interface GetCorporationsCorporationIdFwStatsVictoryPoints { 
    /**
     * Last week\'s victory points gained by members of the given corporation
     */
    last_week: number;
    /**
     * Total victory points gained since the given corporation enlisted
     */
    total: number;
    /**
     * Yesterday\'s victory points gained by members of the given corporation
     */
    yesterday: number;
}

