/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetCharactersCharacterIdLocationOk { 
    /**
     * solar_system_id integer
     */
    solar_system_id: number;
    /**
     * station_id integer
     */
    station_id?: number;
    /**
     * structure_id integer
     */
    structure_id?: number;
}

