/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetCharactersCharacterIdSearchOk { 
    /**
     * agent array
     */
    agent?: Array<number>;
    /**
     * alliance array
     */
    alliance?: Array<number>;
    /**
     * character array
     */
    character?: Array<number>;
    /**
     * constellation array
     */
    constellation?: Array<number>;
    /**
     * corporation array
     */
    corporation?: Array<number>;
    /**
     * faction array
     */
    faction?: Array<number>;
    /**
     * inventory_type array
     */
    inventory_type?: Array<number>;
    /**
     * region array
     */
    region?: Array<number>;
    /**
     * solar_system array
     */
    solar_system?: Array<number>;
    /**
     * station array
     */
    station?: Array<number>;
    /**
     * structure array
     */
    structure?: Array<number>;
}

