/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetCharactersCharacterIdNotificationsContacts200Ok { 
    /**
     * message string
     */
    message: string;
    /**
     * notification_id integer
     */
    notification_id: number;
    /**
     * send_date string
     */
    send_date: string;
    /**
     * sender_character_id integer
     */
    sender_character_id: number;
    /**
     * A number representing the standing level the receiver has been added at by the sender. The standing levels are as follows: -10 -> Terrible | -5 -> Bad |  0 -> Neutral |  5 -> Good |  10 -> Excellent
     */
    standing_level: number;
}

