/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * graphic object
 */
export interface GetCharactersCharacterIdMedalsGraphic { 
    /**
     * color integer
     */
    color?: number;
    /**
     * graphic string
     */
    graphic: string;
    /**
     * layer integer
     */
    layer: number;
    /**
     * part integer
     */
    part: number;
}

