/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Optional object that is returned if a bookmark was made on a planet or a random location in space.
 */
export interface GetCorporationsCorporationIdBookmarksCoordinates { 
    /**
     * x number
     */
    x: number;
    /**
     * y number
     */
    y: number;
    /**
     * z number
     */
    z: number;
}

