/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * wallet transaction
 */
export interface GetCorporationsCorporationIdWalletsDivisionTransactions200Ok { 
    /**
     * client_id integer
     */
    client_id: number;
    /**
     * Date and time of transaction
     */
    date: string;
    /**
     * is_buy boolean
     */
    is_buy: boolean;
    /**
     * -1 if there is no corresponding wallet journal entry
     */
    journal_ref_id: number;
    /**
     * location_id integer
     */
    location_id: number;
    /**
     * quantity integer
     */
    quantity: number;
    /**
     * Unique transaction ID
     */
    transaction_id: number;
    /**
     * type_id integer
     */
    type_id: number;
    /**
     * Amount paid per unit
     */
    unit_price: number;
}

