/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Summary of kills done by the given character against enemy factions
 */
export interface GetCharactersCharacterIdFwStatsKills { 
    /**
     * Last week\'s total number of kills by a given character against enemy factions
     */
    last_week: number;
    /**
     * Total number of kills by a given character against enemy factions since the character enlisted
     */
    total: number;
    /**
     * Yesterday\'s total number of kills by a given character against enemy factions
     */
    yesterday: number;
}

