/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * skill object
 */
export interface GetCharactersCharacterIdSkillsSkill { 
    /**
     * active_skill_level integer
     */
    active_skill_level: number;
    /**
     * skill_id integer
     */
    skill_id: number;
    /**
     * skillpoints_in_skill integer
     */
    skillpoints_in_skill: number;
    /**
     * trained_skill_level integer
     */
    trained_skill_level: number;
}

