/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetCharactersCharacterIdPlanetsPlanetIdHead } from './getCharactersCharacterIdPlanetsPlanetIdHead';


/**
 * extractor_details object
 */
export interface GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails { 
    /**
     * in seconds
     */
    cycle_time?: number;
    /**
     * head_radius number
     */
    head_radius?: number;
    /**
     * heads array
     */
    heads: Array<GetCharactersCharacterIdPlanetsPlanetIdHead>;
    /**
     * product_type_id integer
     */
    product_type_id?: number;
    /**
     * qty_per_cycle integer
     */
    qty_per_cycle?: number;
}

