/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetCharactersCharacterIdFleetOk { 
    /**
     * The character\'s current fleet ID
     */
    fleet_id: number;
    /**
     * Member’s role in fleet
     */
    role: GetCharactersCharacterIdFleetOk.RoleEnum;
    /**
     * ID of the squad the member is in. If not applicable, will be set to -1
     */
    squad_id: number;
    /**
     * ID of the wing the member is in. If not applicable, will be set to -1
     */
    wing_id: number;
}
export namespace GetCharactersCharacterIdFleetOk {
    export type RoleEnum = 'fleet_commander' | 'squad_commander' | 'squad_member' | 'wing_commander';
    export const RoleEnum = {
        FleetCommander: 'fleet_commander' as RoleEnum,
        SquadCommander: 'squad_commander' as RoleEnum,
        SquadMember: 'squad_member' as RoleEnum,
        WingCommander: 'wing_commander' as RoleEnum
    };
}


