/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetCharactersCharacterIdFatigueOk { 
    /**
     * Character\'s jump fatigue expiry
     */
    jump_fatigue_expire_date?: string;
    /**
     * Character\'s last jump activation
     */
    last_jump_date?: string;
    /**
     * Character\'s last jump update
     */
    last_update_date?: string;
}

