/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetCorporationCorporationIdMiningObserversObserverId200Ok { 
    /**
     * The character that did the mining 
     */
    character_id: number;
    /**
     * last_updated string
     */
    last_updated: string;
    /**
     * quantity integer
     */
    quantity: number;
    /**
     * The corporation id of the character at the time data was recorded. 
     */
    recorded_corporation_id: number;
    /**
     * type_id integer
     */
    type_id: number;
}

