/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * fuel object
 */
export interface GetCorporationsCorporationIdStarbasesStarbaseIdFuel { 
    /**
     * quantity integer
     */
    quantity: number;
    /**
     * type_id integer
     */
    type_id: number;
}

