/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * dogma_effect object
 */
export interface GetDogmaDynamicItemsTypeIdItemIdDogmaEffect { 
    /**
     * effect_id integer
     */
    effect_id: number;
    /**
     * is_default boolean
     */
    is_default: boolean;
}

