/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * modifier object
 */
export interface GetDogmaEffectsEffectIdModifier { 
    /**
     * domain string
     */
    domain?: string;
    /**
     * effect_id integer
     */
    effect_id?: number;
    /**
     * func string
     */
    func: string;
    /**
     * modified_attribute_id integer
     */
    modified_attribute_id?: number;
    /**
     * modifying_attribute_id integer
     */
    modifying_attribute_id?: number;
    /**
     * operator integer
     */
    operator?: number;
}

