/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetDogmaDynamicItemsTypeIdItemIdDogmaEffect } from './getDogmaDynamicItemsTypeIdItemIdDogmaEffect';
import { GetDogmaDynamicItemsTypeIdItemIdDogmaAttribute } from './getDogmaDynamicItemsTypeIdItemIdDogmaAttribute';


/**
 * 200 ok object
 */
export interface GetDogmaDynamicItemsTypeIdItemIdOk { 
    /**
     * The ID of the character who created the item
     */
    created_by: number;
    /**
     * dogma_attributes array
     */
    dogma_attributes: Array<GetDogmaDynamicItemsTypeIdItemIdDogmaAttribute>;
    /**
     * dogma_effects array
     */
    dogma_effects: Array<GetDogmaDynamicItemsTypeIdItemIdDogmaEffect>;
    /**
     * The type ID of the mutator used to generate the dynamic item.
     */
    mutator_type_id: number;
    /**
     * The type ID of the source item the mutator was applied to create the dynamic item.
     */
    source_type_id: number;
}

