/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetFwLeaderboardsCharactersActiveTotalActiveTotal1 } from './getFwLeaderboardsCharactersActiveTotalActiveTotal1';
import { GetFwLeaderboardsCharactersYesterdayYesterday1 } from './getFwLeaderboardsCharactersYesterdayYesterday1';
import { GetFwLeaderboardsCharactersLastWeekLastWeek1 } from './getFwLeaderboardsCharactersLastWeekLastWeek1';


/**
 * Top 100 rankings of pilots by victory points from yesterday, last week and in total
 */
export interface GetFwLeaderboardsCharactersVictoryPoints { 
    /**
     * Top 100 ranking of pilots active in faction warfare by total victory points. A pilot is considered \"active\" if they have participated in faction warfare in the past 14 days
     */
    active_total: Array<GetFwLeaderboardsCharactersActiveTotalActiveTotal1>;
    /**
     * Top 100 ranking of pilots by victory points in the past week
     */
    last_week: Array<GetFwLeaderboardsCharactersLastWeekLastWeek1>;
    /**
     * Top 100 ranking of pilots by victory points in the past day
     */
    yesterday: Array<GetFwLeaderboardsCharactersYesterdayYesterday1>;
}

