/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetFwLeaderboardsActiveTotalActiveTotal } from './getFwLeaderboardsActiveTotalActiveTotal';
import { GetFwLeaderboardsYesterdayYesterday } from './getFwLeaderboardsYesterdayYesterday';
import { GetFwLeaderboardsLastWeekLastWeek } from './getFwLeaderboardsLastWeekLastWeek';


/**
 * Top 4 rankings of factions by number of kills from yesterday, last week and in total
 */
export interface GetFwLeaderboardsKills { 
    /**
     * Top 4 ranking of factions active in faction warfare by total kills. A faction is considered \"active\" if they have participated in faction warfare in the past 14 days
     */
    active_total: Array<GetFwLeaderboardsActiveTotalActiveTotal>;
    /**
     * Top 4 ranking of factions by kills in the past week
     */
    last_week: Array<GetFwLeaderboardsLastWeekLastWeek>;
    /**
     * Top 4 ranking of factions by kills in the past day
     */
    yesterday: Array<GetFwLeaderboardsYesterdayYesterday>;
}

