/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * last_week object
 */
export interface GetFwLeaderboardsCharactersLastWeekLastWeek1 { 
    /**
     * Amount of victory points
     */
    amount?: number;
    /**
     * character_id integer
     */
    character_id?: number;
}

