/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetFwLeaderboardsCharactersLastWeekLastWeek } from './getFwLeaderboardsCharactersLastWeekLastWeek';
import { GetFwLeaderboardsCharactersYesterdayYesterday } from './getFwLeaderboardsCharactersYesterdayYesterday';
import { GetFwLeaderboardsCharactersActiveTotalActiveTotal } from './getFwLeaderboardsCharactersActiveTotalActiveTotal';


/**
 * Top 100 rankings of pilots by number of kills from yesterday, last week and in total
 */
export interface GetFwLeaderboardsCharactersKills { 
    /**
     * Top 100 ranking of pilots active in faction warfare by total kills. A pilot is considered \"active\" if they have participated in faction warfare in the past 14 days
     */
    active_total: Array<GetFwLeaderboardsCharactersActiveTotalActiveTotal>;
    /**
     * Top 100 ranking of pilots by kills in the past week
     */
    last_week: Array<GetFwLeaderboardsCharactersLastWeekLastWeek>;
    /**
     * Top 100 ranking of pilots by kills in the past day
     */
    yesterday: Array<GetFwLeaderboardsCharactersYesterdayYesterday>;
}

