/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetFwLeaderboardsVictoryPoints } from './getFwLeaderboardsVictoryPoints';
import { GetFwLeaderboardsKills } from './getFwLeaderboardsKills';


/**
 * 200 ok object
 */
export interface GetFwLeaderboardsOk { 
    kills: GetFwLeaderboardsKills;
    victory_points: GetFwLeaderboardsVictoryPoints;
}

