/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetFwStatsVictoryPoints } from './getFwStatsVictoryPoints';
import { GetFwStatsKills } from './getFwStatsKills';


/**
 * 200 ok object
 */
export interface GetFwStats200Ok { 
    /**
     * faction_id integer
     */
    faction_id: number;
    kills: GetFwStatsKills;
    /**
     * How many pilots fight for the given faction
     */
    pilots: number;
    /**
     * The number of solar systems controlled by the given faction
     */
    systems_controlled: number;
    victory_points: GetFwStatsVictoryPoints;
}

