/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetIndustrySystemsCostIndice } from './getIndustrySystemsCostIndice';


/**
 * 200 ok object
 */
export interface GetIndustrySystems200Ok { 
    /**
     * cost_indices array
     */
    cost_indices: Array<GetIndustrySystemsCostIndice>;
    /**
     * solar_system_id integer
     */
    solar_system_id: number;
}

