/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetIncursions200Ok { 
    /**
     * The constellation id in which this incursion takes place
     */
    constellation_id: number;
    /**
     * The attacking faction\'s id
     */
    faction_id: number;
    /**
     * Whether the final encounter has boss or not
     */
    has_boss: boolean;
    /**
     * A list of infested solar system ids that are a part of this incursion
     */
    infested_solar_systems: Array<number>;
    /**
     * Influence of this incursion as a float from 0 to 1
     */
    influence: number;
    /**
     * Staging solar system for this incursion
     */
    staging_solar_system_id: number;
    /**
     * The state of this incursion
     */
    state: GetIncursions200Ok.StateEnum;
    /**
     * The type of this incursion
     */
    type: string;
}
export namespace GetIncursions200Ok {
    export type StateEnum = 'withdrawing' | 'mobilizing' | 'established';
    export const StateEnum = {
        Withdrawing: 'withdrawing' as StateEnum,
        Mobilizing: 'mobilizing' as StateEnum,
        Established: 'established' as StateEnum
    };
}


