/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetKillmailsKillmailIdKillmailHashItem } from './getKillmailsKillmailIdKillmailHashItem';
import { GetKillmailsKillmailIdKillmailHashPosition } from './getKillmailsKillmailIdKillmailHashPosition';


/**
 * victim object
 */
export interface GetKillmailsKillmailIdKillmailHashVictim { 
    /**
     * alliance_id integer
     */
    alliance_id?: number;
    /**
     * character_id integer
     */
    character_id?: number;
    /**
     * corporation_id integer
     */
    corporation_id?: number;
    /**
     * How much total damage was taken by the victim 
     */
    damage_taken: number;
    /**
     * faction_id integer
     */
    faction_id?: number;
    /**
     * items array
     */
    items?: Array<GetKillmailsKillmailIdKillmailHashItem>;
    position?: GetKillmailsKillmailIdKillmailHashPosition;
    /**
     * The ship that the victim was piloting and was destroyed 
     */
    ship_type_id: number;
}

