/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetLoyaltyStoresCorporationIdOffersRequiredItem } from './getLoyaltyStoresCorporationIdOffersRequiredItem';


/**
 * 200 ok object
 */
export interface GetLoyaltyStoresCorporationIdOffers200Ok { 
    /**
     * Analysis kredit cost
     */
    ak_cost?: number;
    /**
     * isk_cost integer
     */
    isk_cost: number;
    /**
     * lp_cost integer
     */
    lp_cost: number;
    /**
     * offer_id integer
     */
    offer_id: number;
    /**
     * quantity integer
     */
    quantity: number;
    /**
     * required_items array
     */
    required_items: Array<GetLoyaltyStoresCorporationIdOffersRequiredItem>;
    /**
     * type_id integer
     */
    type_id: number;
}

