/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetMarketsStructuresStructureId200Ok { 
    /**
     * duration integer
     */
    duration: number;
    /**
     * is_buy_order boolean
     */
    is_buy_order: boolean;
    /**
     * issued string
     */
    issued: string;
    /**
     * location_id integer
     */
    location_id: number;
    /**
     * min_volume integer
     */
    min_volume: number;
    /**
     * order_id integer
     */
    order_id: number;
    /**
     * price number
     */
    price: number;
    /**
     * range string
     */
    range: GetMarketsStructuresStructureId200Ok.RangeEnum;
    /**
     * type_id integer
     */
    type_id: number;
    /**
     * volume_remain integer
     */
    volume_remain: number;
    /**
     * volume_total integer
     */
    volume_total: number;
}
export namespace GetMarketsStructuresStructureId200Ok {
    export type RangeEnum = 'station' | 'region' | 'solarsystem' | '1' | '2' | '3' | '4' | '5' | '10' | '20' | '30' | '40';
    export const RangeEnum = {
        Station: 'station' as RangeEnum,
        Region: 'region' as RangeEnum,
        Solarsystem: 'solarsystem' as RangeEnum,
        _1: '1' as RangeEnum,
        _2: '2' as RangeEnum,
        _3: '3' as RangeEnum,
        _4: '4' as RangeEnum,
        _5: '5' as RangeEnum,
        _10: '10' as RangeEnum,
        _20: '20' as RangeEnum,
        _30: '30' as RangeEnum,
        _40: '40' as RangeEnum
    };
}


