/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetOpportunitiesGroupsGroupIdOk { 
    /**
     * The groups that are connected to this group on the opportunities map
     */
    connected_groups: Array<number>;
    /**
     * description string
     */
    description: string;
    /**
     * group_id integer
     */
    group_id: number;
    /**
     * name string
     */
    name: string;
    /**
     * notification string
     */
    notification: string;
    /**
     * Tasks need to complete for this group
     */
    required_tasks: Array<number>;
}

