/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * participant object
 */
export interface GetSovereigntyCampaignsParticipant { 
    /**
     * alliance_id integer
     */
    alliance_id: number;
    /**
     * score number
     */
    score: number;
}

