/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * destination object
 */
export interface GetUniverseStargatesStargateIdDestination { 
    /**
     * The stargate this stargate connects to
     */
    stargate_id: number;
    /**
     * The solar system this stargate connects to
     */
    system_id: number;
}

