/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Coordinates of the structure in Cartesian space relative to the Sun, in metres. 
 */
export interface GetUniverseStructuresStructureIdPosition { 
    /**
     * x number
     */
    x: number;
    /**
     * y number
     */
    y: number;
    /**
     * z number
     */
    z: number;
}

