/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetUniverseAsteroidBeltsAsteroidBeltIdPosition } from './getUniverseAsteroidBeltsAsteroidBeltIdPosition';


/**
 * 200 ok object
 */
export interface GetUniverseAsteroidBeltsAsteroidBeltIdOk { 
    /**
     * name string
     */
    name: string;
    position: GetUniverseAsteroidBeltsAsteroidBeltIdPosition;
    /**
     * The solar system this asteroid belt is in
     */
    system_id: number;
}

