/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetUniverseStarsStarIdOk { 
    /**
     * Age of star in years
     */
    age: number;
    /**
     * luminosity number
     */
    luminosity: number;
    /**
     * name string
     */
    name: string;
    /**
     * radius integer
     */
    radius: number;
    /**
     * solar_system_id integer
     */
    solar_system_id: number;
    /**
     * spectral_class string
     */
    spectral_class: GetUniverseStarsStarIdOk.SpectralClassEnum;
    /**
     * temperature integer
     */
    temperature: number;
    /**
     * type_id integer
     */
    type_id: number;
}
export namespace GetUniverseStarsStarIdOk {
    export type SpectralClassEnum = 'K2 V' | 'K4 V' | 'G2 V' | 'G8 V' | 'M7 V' | 'K7 V' | 'M2 V' | 'K5 V' | 'M3 V' | 'G0 V' | 'G7 V' | 'G3 V' | 'F9 V' | 'G5 V' | 'F6 V' | 'K8 V' | 'K9 V' | 'K6 V' | 'G9 V' | 'G6 V' | 'G4 VI' | 'G4 V' | 'F8 V' | 'F2 V' | 'F1 V' | 'K3 V' | 'F0 VI' | 'G1 VI' | 'G0 VI' | 'K1 V' | 'M4 V' | 'M1 V' | 'M6 V' | 'M0 V' | 'K2 IV' | 'G2 VI' | 'K0 V' | 'K5 IV' | 'F5 VI' | 'G6 VI' | 'F6 VI' | 'F2 IV' | 'G3 VI' | 'M8 V' | 'F1 VI' | 'K1 IV' | 'F7 V' | 'G5 VI' | 'M5 V' | 'G7 VI' | 'F5 V' | 'F4 VI' | 'F8 VI' | 'K3 IV' | 'F4 IV' | 'F0 V' | 'G7 IV' | 'G8 VI' | 'F2 VI' | 'F4 V' | 'F7 VI' | 'F3 V' | 'G1 V' | 'G9 VI' | 'F3 IV' | 'F9 VI' | 'M9 V' | 'K0 IV' | 'F1 IV' | 'G4 IV' | 'F3 VI' | 'K4 IV' | 'G5 IV' | 'G3 IV' | 'G1 IV' | 'K7 IV' | 'G0 IV' | 'K6 IV' | 'K9 IV' | 'G2 IV' | 'F9 IV' | 'F0 IV' | 'K8 IV' | 'G8 IV' | 'F6 IV' | 'F5 IV' | 'A0' | 'A0IV' | 'A0IV2';
    export const SpectralClassEnum = {
        K2V: 'K2 V' as SpectralClassEnum,
        K4V: 'K4 V' as SpectralClassEnum,
        G2V: 'G2 V' as SpectralClassEnum,
        G8V: 'G8 V' as SpectralClassEnum,
        M7V: 'M7 V' as SpectralClassEnum,
        K7V: 'K7 V' as SpectralClassEnum,
        M2V: 'M2 V' as SpectralClassEnum,
        K5V: 'K5 V' as SpectralClassEnum,
        M3V: 'M3 V' as SpectralClassEnum,
        G0V: 'G0 V' as SpectralClassEnum,
        G7V: 'G7 V' as SpectralClassEnum,
        G3V: 'G3 V' as SpectralClassEnum,
        F9V: 'F9 V' as SpectralClassEnum,
        G5V: 'G5 V' as SpectralClassEnum,
        F6V: 'F6 V' as SpectralClassEnum,
        K8V: 'K8 V' as SpectralClassEnum,
        K9V: 'K9 V' as SpectralClassEnum,
        K6V: 'K6 V' as SpectralClassEnum,
        G9V: 'G9 V' as SpectralClassEnum,
        G6V: 'G6 V' as SpectralClassEnum,
        G4Vi: 'G4 VI' as SpectralClassEnum,
        G4V: 'G4 V' as SpectralClassEnum,
        F8V: 'F8 V' as SpectralClassEnum,
        F2V: 'F2 V' as SpectralClassEnum,
        F1V: 'F1 V' as SpectralClassEnum,
        K3V: 'K3 V' as SpectralClassEnum,
        F0Vi: 'F0 VI' as SpectralClassEnum,
        G1Vi: 'G1 VI' as SpectralClassEnum,
        G0Vi: 'G0 VI' as SpectralClassEnum,
        K1V: 'K1 V' as SpectralClassEnum,
        M4V: 'M4 V' as SpectralClassEnum,
        M1V: 'M1 V' as SpectralClassEnum,
        M6V: 'M6 V' as SpectralClassEnum,
        M0V: 'M0 V' as SpectralClassEnum,
        K2Iv: 'K2 IV' as SpectralClassEnum,
        G2Vi: 'G2 VI' as SpectralClassEnum,
        K0V: 'K0 V' as SpectralClassEnum,
        K5Iv: 'K5 IV' as SpectralClassEnum,
        F5Vi: 'F5 VI' as SpectralClassEnum,
        G6Vi: 'G6 VI' as SpectralClassEnum,
        F6Vi: 'F6 VI' as SpectralClassEnum,
        F2Iv: 'F2 IV' as SpectralClassEnum,
        G3Vi: 'G3 VI' as SpectralClassEnum,
        M8V: 'M8 V' as SpectralClassEnum,
        F1Vi: 'F1 VI' as SpectralClassEnum,
        K1Iv: 'K1 IV' as SpectralClassEnum,
        F7V: 'F7 V' as SpectralClassEnum,
        G5Vi: 'G5 VI' as SpectralClassEnum,
        M5V: 'M5 V' as SpectralClassEnum,
        G7Vi: 'G7 VI' as SpectralClassEnum,
        F5V: 'F5 V' as SpectralClassEnum,
        F4Vi: 'F4 VI' as SpectralClassEnum,
        F8Vi: 'F8 VI' as SpectralClassEnum,
        K3Iv: 'K3 IV' as SpectralClassEnum,
        F4Iv: 'F4 IV' as SpectralClassEnum,
        F0V: 'F0 V' as SpectralClassEnum,
        G7Iv: 'G7 IV' as SpectralClassEnum,
        G8Vi: 'G8 VI' as SpectralClassEnum,
        F2Vi: 'F2 VI' as SpectralClassEnum,
        F4V: 'F4 V' as SpectralClassEnum,
        F7Vi: 'F7 VI' as SpectralClassEnum,
        F3V: 'F3 V' as SpectralClassEnum,
        G1V: 'G1 V' as SpectralClassEnum,
        G9Vi: 'G9 VI' as SpectralClassEnum,
        F3Iv: 'F3 IV' as SpectralClassEnum,
        F9Vi: 'F9 VI' as SpectralClassEnum,
        M9V: 'M9 V' as SpectralClassEnum,
        K0Iv: 'K0 IV' as SpectralClassEnum,
        F1Iv: 'F1 IV' as SpectralClassEnum,
        G4Iv: 'G4 IV' as SpectralClassEnum,
        F3Vi: 'F3 VI' as SpectralClassEnum,
        K4Iv: 'K4 IV' as SpectralClassEnum,
        G5Iv: 'G5 IV' as SpectralClassEnum,
        G3Iv: 'G3 IV' as SpectralClassEnum,
        G1Iv: 'G1 IV' as SpectralClassEnum,
        K7Iv: 'K7 IV' as SpectralClassEnum,
        G0Iv: 'G0 IV' as SpectralClassEnum,
        K6Iv: 'K6 IV' as SpectralClassEnum,
        K9Iv: 'K9 IV' as SpectralClassEnum,
        G2Iv: 'G2 IV' as SpectralClassEnum,
        F9Iv: 'F9 IV' as SpectralClassEnum,
        F0Iv: 'F0 IV' as SpectralClassEnum,
        K8Iv: 'K8 IV' as SpectralClassEnum,
        G8Iv: 'G8 IV' as SpectralClassEnum,
        F6Iv: 'F6 IV' as SpectralClassEnum,
        F5Iv: 'F5 IV' as SpectralClassEnum,
        A0: 'A0' as SpectralClassEnum,
        A0Iv: 'A0IV' as SpectralClassEnum,
        A0Iv2: 'A0IV2' as SpectralClassEnum
    };
}


