/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetUniverseMoonsMoonIdPosition } from './getUniverseMoonsMoonIdPosition';


/**
 * 200 ok object
 */
export interface GetUniverseMoonsMoonIdOk { 
    /**
     * moon_id integer
     */
    moon_id: number;
    /**
     * name string
     */
    name: string;
    position: GetUniverseMoonsMoonIdPosition;
    /**
     * The solar system this moon is in
     */
    system_id: number;
}

