/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetUniversePlanetsPlanetIdPosition } from './getUniversePlanetsPlanetIdPosition';


/**
 * 200 ok object
 */
export interface GetUniversePlanetsPlanetIdOk { 
    /**
     * name string
     */
    name: string;
    /**
     * planet_id integer
     */
    planet_id: number;
    position: GetUniversePlanetsPlanetIdPosition;
    /**
     * The solar system this planet is in
     */
    system_id: number;
    /**
     * type_id integer
     */
    type_id: number;
}

