/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetUniverseAncestries200Ok { 
    /**
     * The bloodline associated with this ancestry
     */
    bloodline_id: number;
    /**
     * description string
     */
    description: string;
    /**
     * icon_id integer
     */
    icon_id?: number;
    /**
     * id integer
     */
    id: number;
    /**
     * name string
     */
    name: string;
    /**
     * short_description string
     */
    short_description?: string;
}

