/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The defending corporation or alliance that declared this war, only contains either corporation_id or alliance_id
 */
export interface GetWarsWarIdDefender { 
    /**
     * Alliance ID if and only if the defender is an alliance
     */
    alliance_id?: number;
    /**
     * Corporation ID if and only if the defender is a corporation
     */
    corporation_id?: number;
    /**
     * ISK value of ships the defender has killed
     */
    isk_destroyed: number;
    /**
     * The number of ships the defender has killed
     */
    ships_killed: number;
}

