/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ally object
 */
export interface GetWarsWarIdAlly { 
    /**
     * Alliance ID if and only if this ally is an alliance
     */
    alliance_id?: number;
    /**
     * Corporation ID if and only if this ally is a corporation
     */
    corporation_id?: number;
}

