/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 201 created object
 */
export interface PostFleetsFleetIdWingsCreated { 
    /**
     * The wing_id of the newly created wing
     */
    wing_id: number;
}

