/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * new_mail object
 */
export interface PostUiOpenwindowNewmailNewMail { 
    /**
     * body string
     */
    body: string;
    /**
     * recipients array
     */
    recipients: Array<number>;
    /**
     * subject string
     */
    subject: string;
    /**
     * to_corp_or_alliance_id integer
     */
    to_corp_or_alliance_id?: number;
    /**
     * Corporations, alliances and mailing lists are all types of mailing groups. You may only send to one mailing group, at a time, so you may fill out either this field or the to_corp_or_alliance_ids field
     */
    to_mailing_list_id?: number;
}

