/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * response object
 */
export interface PutCharactersCharacterIdCalendarEventIdResponse { 
    /**
     * response string
     */
    response: PutCharactersCharacterIdCalendarEventIdResponse.ResponseEnum;
}
export namespace PutCharactersCharacterIdCalendarEventIdResponse {
    export type ResponseEnum = 'accepted' | 'declined' | 'tentative';
    export const ResponseEnum = {
        Accepted: 'accepted' as ResponseEnum,
        Declined: 'declined' as ResponseEnum,
        Tentative: 'tentative' as ResponseEnum
    };
}


