apiVersion: v1
kind: Service
metadata:
  name: nin-svc
  namespace: neocom
spec:
  selector:
    app: nin-$ENV
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: $PORT
      nodePort: 30010

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nin-$ENV
  namespace: neocom
  labels:
    app: nin-$ENV
    version: $VERSION
    port: $PORT
    module: neocom-infinity-nest
    build: $VERSION
spec:
  selector:
    matchLabels:
      app: nin-$ENV
  template:
    spec:
      containers:
      - name: nin-$ENV
        image: adamantinoo/$IMAGE_NAME:$VERSION
        env:
        - name: NODE_ENV
          value: "$ENV"
        ports:
        - containerPort: $PORT
        imagePullPolicy: Always
      serviceAccountName: default
