version: '3'
services:
  neocom-frontend-backend-simulator:
    container_name: neocom-frontend-backend-simulator
    image: apimastery/apisimulator:1.6
    ports:
      - "5210:6090"
    volumes:
      # WARNING - Use full absolute paths to make this work.
      - /home/adam/Development/NeoCom0.20/NeoCom-Infinity/NeoCom-Infinity-Frontend/support/backend-simulation:/backend-simulation
    command: "bin/apisimulator start /backend-simulation -p 6090"

  backend-postgres-development:
    container_name: backend-postgres-development
    image: "postgres:11.2"
    ports:
      - "5230:5432"
    environment:
      - CURRENT_UID=1000
      - POSTGRES_DB=postgres
      - POSTGRES_USER=neocom-user
      - POSTGRES_PASSWORD=neocom-password

  neocom-frontend-backend:
    container_name: neocom-frontend-backend
    image: neocom/neocom-infinity.backend
    ports:
      - "5220:9500"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - PROFILE=development
      - JDBC_DATABASE_URL=jdbc:postgresql://backend-postgres-development:5432/postgres
      - DB_USER=neocom-user
      - DB_PASSWORD=neocom-password
      - NEOCOM_DATABASE_URL=jdbc:postgresql://backend-postgres-development:5432/postgres?user=neocom-user&password=neocom-password
      - DEFAULT_BACKEND_SERVER="http://localhost:"
      - NEOCOM_BANNER_LOCATION=./app-banner.txt
      - PROPERTIES_DIRECTORY=/properties-dev
      - APPLICATION_DIRECTORY=./NeoCom.Infinity.Development
      - SDE_DATABASE_PATH=./sde.db
