version: '3'
services:
  neocom-frontend-backend-simulator:
    container_name: neocom-frontend-backend-simulator
    image: apimastery/apisimulator:1.6
    ports:
      - "5210:6090"
    volumes:
      # WARNING - Use full absolute paths to make this work.
      - /home/adam/Development/NeoCom0.20/NeoCom-Infinity/NeoCom-Infinity-Frontend/support/backend-simulation:/backend-simulation
    command: "bin/apisimulator start /backend-simulation -p 6090"
