/**
 * NeoCom Infinity - NestJS Backend Api v.0.20.0
 * This is the Rest Api definition for the NeoCom Infinity Backend services. This new set of services are being developed with NestJs that is a Typescript backend framework code compatible with the Angular Frontend.  The new backend starts at version 0.20.0 for the new Infinity feature set. The server will export the Api endpoints to Access some of the Esi Data Source CCP published endpoints and on some cases it will expand Esi features and enrich data.
 *
 * The version of the OpenAPI document: 0.21.0
 * Contact: adamantinoo.git@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ErrorResponse { 
    code: string;
    message: string;
}

