/**
 * NeoCom Infinity - NestJS Backend Api v.0.20.0
 * This is the Rest Api definition for the NeoCom Infinity Backend services. This new set of services are being developed with NestJs that is a Typescript backend framework code compatible with the Angular Frontend.  The new backend starts at version 0.20.0 for the new Infinity feature set. The server will export the Api endpoints to Access some of the Esi Data Source CCP published endpoints and on some cases it will expand Esi features and enrich data.
 *
 * The version of the OpenAPI document: 0.21.0
 * Contact: adamantinoo.git@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MiningOperation { 
    /**
     * The class of the Json object that is being described.
     */
    jsonClass: string;
    /**
     * The unique identifier for a mining operation. Is composed of the date, the eve system  identifier and the type of the ore that is being represented on the mining operation. 
     */
    id: string;
    /**
     * The extraction date for this ore. Each extraction is aggegated by date and ore type.
     */
    date: string;
    /**
     * The ore stack size or the ore quentity extracted.
     */
    quantity: number;
    /**
     * The Eve system unique identifier where the ore was extracted.
     */
    solarSystem: number;
    /**
     * The Eve unique identifier for the extracted ore type.
     */
    type: number;
}

