# - DEFINITION FOR THE ESI SSO AUTHENTICATION APPLICATION
# - NEOCOM INFINITY SPRING BOOT - NEOCOM.INFINITY - HEROKU - STAGING
P.esi.tranquility.authorization.agent=Dimensinfin Industries 2024 : Spring Boot 2 backend client : Staging
P.esi.tranquility.authorization.content.type=application/x-www-form-urlencoded

P.esi.tranquility.authorization.server.url=https://login.eveonline.com/
P.esi.tranquility.authorization.clientid=e38a584ae3df42c4a2adeb15efb3badb
P.esi.tranquility.authorization.secretkey=cD5FcqfCC66I4wxw7xyvbxOVUYhQLYJ472t5KcCJ
P.esi.tranquility.authorization.callback=http://localhost:32100/app/loginValidation
P.esi.tranquility.authorization.state=-NEOCOM.INFINITY-PRODUCTION-VALID STATE STRING-
P.esi.tranquility.authorization.accesstoken.url=oauth/token
P.esi.tranquility.authorization.authorize.url=oauth/authorize
