/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * service object
 */
export interface GetCorporationsCorporationIdStructuresService { 
    /**
     * name string
     */
    name: string;
    /**
     * state string
     */
    state: GetCorporationsCorporationIdStructuresService.StateEnum;
}
export namespace GetCorporationsCorporationIdStructuresService {
    export type StateEnum = 'online' | 'offline' | 'cleanup';
    export const StateEnum = {
        Online: 'online' as StateEnum,
        Offline: 'offline' as StateEnum,
        Cleanup: 'cleanup' as StateEnum
    };
}


