/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetCharactersCharacterIdFwStatsKills } from './getCharactersCharacterIdFwStatsKills';
import { GetCharactersCharacterIdFwStatsVictoryPoints } from './getCharactersCharacterIdFwStatsVictoryPoints';


/**
 * 200 ok object
 */
export interface GetCharactersCharacterIdFwStatsOk { 
    /**
     * The given character\'s current faction rank
     */
    current_rank?: number;
    /**
     * The enlistment date of the given character into faction warfare. Will not be included if character is not enlisted in faction warfare
     */
    enlisted_on?: string;
    /**
     * The faction the given character is enlisted to fight for. Will not be included if character is not enlisted in faction warfare
     */
    faction_id?: number;
    /**
     * The given character\'s highest faction rank achieved
     */
    highest_rank?: number;
    kills: GetCharactersCharacterIdFwStatsKills;
    victory_points: GetCharactersCharacterIdFwStatsVictoryPoints;
}

