/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * character_id and response of an attendee
 */
export interface GetCharactersCharacterIdCalendarEventIdAttendees200Ok { 
    /**
     * character_id integer
     */
    character_id?: number;
    /**
     * event_response string
     */
    event_response?: GetCharactersCharacterIdCalendarEventIdAttendees200Ok.EventResponseEnum;
}
export namespace GetCharactersCharacterIdCalendarEventIdAttendees200Ok {
    export type EventResponseEnum = 'declined' | 'not_responded' | 'accepted' | 'tentative';
    export const EventResponseEnum = {
        Declined: 'declined' as EventResponseEnum,
        NotResponded: 'not_responded' as EventResponseEnum,
        Accepted: 'accepted' as EventResponseEnum,
        Tentative: 'tentative' as EventResponseEnum
    };
}


