/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetCharactersCharacterIdPlanetsPlanetIdLink } from './getCharactersCharacterIdPlanetsPlanetIdLink';
import { GetCharactersCharacterIdPlanetsPlanetIdPin } from './getCharactersCharacterIdPlanetsPlanetIdPin';
import { GetCharactersCharacterIdPlanetsPlanetIdRoute } from './getCharactersCharacterIdPlanetsPlanetIdRoute';


/**
 * 200 ok object
 */
export interface GetCharactersCharacterIdPlanetsPlanetIdOk { 
    /**
     * links array
     */
    links: Array<GetCharactersCharacterIdPlanetsPlanetIdLink>;
    /**
     * pins array
     */
    pins: Array<GetCharactersCharacterIdPlanetsPlanetIdPin>;
    /**
     * routes array
     */
    routes: Array<GetCharactersCharacterIdPlanetsPlanetIdRoute>;
}

