/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * link object
 */
export interface GetCharactersCharacterIdPlanetsPlanetIdLink { 
    /**
     * destination_pin_id integer
     */
    destination_pin_id: number;
    /**
     * link_level integer
     */
    link_level: number;
    /**
     * source_pin_id integer
     */
    source_pin_id: number;
}

