/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetCharactersCharacterIdMailLabelsLabel } from './getCharactersCharacterIdMailLabelsLabel';


/**
 * 200 ok object
 */
export interface GetCharactersCharacterIdMailLabelsOk { 
    /**
     * labels array
     */
    labels?: Array<GetCharactersCharacterIdMailLabelsLabel>;
    /**
     * total_unread_count integer
     */
    total_unread_count?: number;
}

