/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * head object
 */
export interface GetCharactersCharacterIdPlanetsPlanetIdHead { 
    /**
     * head_id integer
     */
    head_id: number;
    /**
     * latitude number
     */
    latitude: number;
    /**
     * longitude number
     */
    longitude: number;
}

