/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetCorporationsCorporationIdStandings200Ok { 
    /**
     * from_id integer
     */
    from_id: number;
    /**
     * from_type string
     */
    from_type: GetCorporationsCorporationIdStandings200Ok.FromTypeEnum;
    /**
     * standing number
     */
    standing: number;
}
export namespace GetCorporationsCorporationIdStandings200Ok {
    export type FromTypeEnum = 'agent' | 'npc_corp' | 'faction';
    export const FromTypeEnum = {
        Agent: 'agent' as FromTypeEnum,
        NpcCorp: 'npc_corp' as FromTypeEnum,
        Faction: 'faction' as FromTypeEnum
    };
}


