/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * jump_clone object
 */
export interface GetCharactersCharacterIdClonesJumpClone { 
    /**
     * implants array
     */
    implants: Array<number>;
    /**
     * jump_clone_id integer
     */
    jump_clone_id: number;
    /**
     * location_id integer
     */
    location_id: number;
    /**
     * location_type string
     */
    location_type: GetCharactersCharacterIdClonesJumpClone.LocationTypeEnum;
    /**
     * name string
     */
    name?: string;
}
export namespace GetCharactersCharacterIdClonesJumpClone {
    export type LocationTypeEnum = 'station' | 'structure';
    export const LocationTypeEnum = {
        Station: 'station' as LocationTypeEnum,
        Structure: 'structure' as LocationTypeEnum
    };
}


