/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetCharactersCharacterIdPlanets200Ok { 
    /**
     * last_update string
     */
    last_update: string;
    /**
     * num_pins integer
     */
    num_pins: number;
    /**
     * owner_id integer
     */
    owner_id: number;
    /**
     * planet_id integer
     */
    planet_id: number;
    /**
     * planet_type string
     */
    planet_type: GetCharactersCharacterIdPlanets200Ok.PlanetTypeEnum;
    /**
     * solar_system_id integer
     */
    solar_system_id: number;
    /**
     * upgrade_level integer
     */
    upgrade_level: number;
}
export namespace GetCharactersCharacterIdPlanets200Ok {
    export type PlanetTypeEnum = 'temperate' | 'barren' | 'oceanic' | 'ice' | 'gas' | 'lava' | 'storm' | 'plasma';
    export const PlanetTypeEnum = {
        Temperate: 'temperate' as PlanetTypeEnum,
        Barren: 'barren' as PlanetTypeEnum,
        Oceanic: 'oceanic' as PlanetTypeEnum,
        Ice: 'ice' as PlanetTypeEnum,
        Gas: 'gas' as PlanetTypeEnum,
        Lava: 'lava' as PlanetTypeEnum,
        Storm: 'storm' as PlanetTypeEnum,
        Plasma: 'plasma' as PlanetTypeEnum
    };
}


