/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetCorporationsCorporationIdMedals200Ok { 
    /**
     * created_at string
     */
    created_at: string;
    /**
     * ID of the character who created this medal
     */
    creator_id: number;
    /**
     * description string
     */
    description: string;
    /**
     * medal_id integer
     */
    medal_id: number;
    /**
     * title string
     */
    title: string;
}

