/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * item object
 */
export interface GetCharactersCharacterIdFittingsItem { 
    /**
     * flag string
     */
    flag: GetCharactersCharacterIdFittingsItem.FlagEnum;
    /**
     * quantity integer
     */
    quantity: number;
    /**
     * type_id integer
     */
    type_id: number;
}
export namespace GetCharactersCharacterIdFittingsItem {
    export type FlagEnum = 'Cargo' | 'DroneBay' | 'FighterBay' | 'HiSlot0' | 'HiSlot1' | 'HiSlot2' | 'HiSlot3' | 'HiSlot4' | 'HiSlot5' | 'HiSlot6' | 'HiSlot7' | 'Invalid' | 'LoSlot0' | 'LoSlot1' | 'LoSlot2' | 'LoSlot3' | 'LoSlot4' | 'LoSlot5' | 'LoSlot6' | 'LoSlot7' | 'MedSlot0' | 'MedSlot1' | 'MedSlot2' | 'MedSlot3' | 'MedSlot4' | 'MedSlot5' | 'MedSlot6' | 'MedSlot7' | 'RigSlot0' | 'RigSlot1' | 'RigSlot2' | 'ServiceSlot0' | 'ServiceSlot1' | 'ServiceSlot2' | 'ServiceSlot3' | 'ServiceSlot4' | 'ServiceSlot5' | 'ServiceSlot6' | 'ServiceSlot7' | 'SubSystemSlot0' | 'SubSystemSlot1' | 'SubSystemSlot2' | 'SubSystemSlot3';
    export const FlagEnum = {
        Cargo: 'Cargo' as FlagEnum,
        DroneBay: 'DroneBay' as FlagEnum,
        FighterBay: 'FighterBay' as FlagEnum,
        HiSlot0: 'HiSlot0' as FlagEnum,
        HiSlot1: 'HiSlot1' as FlagEnum,
        HiSlot2: 'HiSlot2' as FlagEnum,
        HiSlot3: 'HiSlot3' as FlagEnum,
        HiSlot4: 'HiSlot4' as FlagEnum,
        HiSlot5: 'HiSlot5' as FlagEnum,
        HiSlot6: 'HiSlot6' as FlagEnum,
        HiSlot7: 'HiSlot7' as FlagEnum,
        Invalid: 'Invalid' as FlagEnum,
        LoSlot0: 'LoSlot0' as FlagEnum,
        LoSlot1: 'LoSlot1' as FlagEnum,
        LoSlot2: 'LoSlot2' as FlagEnum,
        LoSlot3: 'LoSlot3' as FlagEnum,
        LoSlot4: 'LoSlot4' as FlagEnum,
        LoSlot5: 'LoSlot5' as FlagEnum,
        LoSlot6: 'LoSlot6' as FlagEnum,
        LoSlot7: 'LoSlot7' as FlagEnum,
        MedSlot0: 'MedSlot0' as FlagEnum,
        MedSlot1: 'MedSlot1' as FlagEnum,
        MedSlot2: 'MedSlot2' as FlagEnum,
        MedSlot3: 'MedSlot3' as FlagEnum,
        MedSlot4: 'MedSlot4' as FlagEnum,
        MedSlot5: 'MedSlot5' as FlagEnum,
        MedSlot6: 'MedSlot6' as FlagEnum,
        MedSlot7: 'MedSlot7' as FlagEnum,
        RigSlot0: 'RigSlot0' as FlagEnum,
        RigSlot1: 'RigSlot1' as FlagEnum,
        RigSlot2: 'RigSlot2' as FlagEnum,
        ServiceSlot0: 'ServiceSlot0' as FlagEnum,
        ServiceSlot1: 'ServiceSlot1' as FlagEnum,
        ServiceSlot2: 'ServiceSlot2' as FlagEnum,
        ServiceSlot3: 'ServiceSlot3' as FlagEnum,
        ServiceSlot4: 'ServiceSlot4' as FlagEnum,
        ServiceSlot5: 'ServiceSlot5' as FlagEnum,
        ServiceSlot6: 'ServiceSlot6' as FlagEnum,
        ServiceSlot7: 'ServiceSlot7' as FlagEnum,
        SubSystemSlot0: 'SubSystemSlot0' as FlagEnum,
        SubSystemSlot1: 'SubSystemSlot1' as FlagEnum,
        SubSystemSlot2: 'SubSystemSlot2' as FlagEnum,
        SubSystemSlot3: 'SubSystemSlot3' as FlagEnum
    };
}


