/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Summary of victory points gained by the given character for the enlisted faction
 */
export interface GetCharactersCharacterIdFwStatsVictoryPoints { 
    /**
     * Last week\'s victory points gained by the given character
     */
    last_week: number;
    /**
     * Total victory points gained since the given character enlisted
     */
    total: number;
    /**
     * Yesterday\'s victory points gained by the given character
     */
    yesterday: number;
}

