/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * route object
 */
export interface GetCharactersCharacterIdPlanetsPlanetIdRoute { 
    /**
     * content_type_id integer
     */
    content_type_id: number;
    /**
     * destination_pin_id integer
     */
    destination_pin_id: number;
    /**
     * quantity number
     */
    quantity: number;
    /**
     * route_id integer
     */
    route_id: number;
    /**
     * source_pin_id integer
     */
    source_pin_id: number;
    /**
     * list of pin ID waypoints
     */
    waypoints?: Array<number>;
}

