/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetCorporationCorporationIdMiningExtractions200Ok { 
    /**
     * The time at which the chunk being extracted will arrive and can be fractured by the moon mining drill. 
     */
    chunk_arrival_time: string;
    /**
     * The time at which the current extraction was initiated. 
     */
    extraction_start_time: string;
    /**
     * moon_id integer
     */
    moon_id: number;
    /**
     * The time at which the chunk being extracted will naturally fracture if it is not first fractured by the moon mining drill. 
     */
    natural_decay_time: string;
    /**
     * structure_id integer
     */
    structure_id: number;
}

