/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * active_total object
 */
export interface GetFwLeaderboardsCorporationsActiveTotalActiveTotal { 
    /**
     * Amount of kills
     */
    amount?: number;
    /**
     * corporation_id integer
     */
    corporation_id?: number;
}

