/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetFwLeaderboardsActiveTotalActiveTotal1 } from './getFwLeaderboardsActiveTotalActiveTotal1';
import { GetFwLeaderboardsLastWeekLastWeek1 } from './getFwLeaderboardsLastWeekLastWeek1';
import { GetFwLeaderboardsYesterdayYesterday1 } from './getFwLeaderboardsYesterdayYesterday1';


/**
 * Top 4 rankings of factions by victory points from yesterday, last week and in total
 */
export interface GetFwLeaderboardsVictoryPoints { 
    /**
     * Top 4 ranking of factions active in faction warfare by total victory points. A faction is considered \"active\" if they have participated in faction warfare in the past 14 days
     */
    active_total: Array<GetFwLeaderboardsActiveTotalActiveTotal1>;
    /**
     * Top 4 ranking of factions by victory points in the past week
     */
    last_week: Array<GetFwLeaderboardsLastWeekLastWeek1>;
    /**
     * Top 4 ranking of factions by victory points in the past day
     */
    yesterday: Array<GetFwLeaderboardsYesterdayYesterday1>;
}

