/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * cost_indice object
 */
export interface GetIndustrySystemsCostIndice { 
    /**
     * activity string
     */
    activity: GetIndustrySystemsCostIndice.ActivityEnum;
    /**
     * cost_index number
     */
    cost_index: number;
}
export namespace GetIndustrySystemsCostIndice {
    export type ActivityEnum = 'copying' | 'duplicating' | 'invention' | 'manufacturing' | 'none' | 'reaction' | 'researching_material_efficiency' | 'researching_technology' | 'researching_time_efficiency' | 'reverse_engineering';
    export const ActivityEnum = {
        Copying: 'copying' as ActivityEnum,
        Duplicating: 'duplicating' as ActivityEnum,
        Invention: 'invention' as ActivityEnum,
        Manufacturing: 'manufacturing' as ActivityEnum,
        None: 'none' as ActivityEnum,
        Reaction: 'reaction' as ActivityEnum,
        ResearchingMaterialEfficiency: 'researching_material_efficiency' as ActivityEnum,
        ResearchingTechnology: 'researching_technology' as ActivityEnum,
        ResearchingTimeEfficiency: 'researching_time_efficiency' as ActivityEnum,
        ReverseEngineering: 'reverse_engineering' as ActivityEnum
    };
}


