/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * level object
 */
export interface GetInsurancePricesLevel { 
    /**
     * cost number
     */
    cost: number;
    /**
     * Localized insurance level
     */
    name: string;
    /**
     * payout number
     */
    payout: number;
}

