/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetInsurancePricesLevel } from './getInsurancePricesLevel';


/**
 * 200 ok object
 */
export interface GetInsurancePrices200Ok { 
    /**
     * A list of a available insurance levels for this ship type
     */
    levels: Array<GetInsurancePricesLevel>;
    /**
     * type_id integer
     */
    type_id: number;
}

