/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetMarketsRegionIdHistory200Ok { 
    /**
     * average number
     */
    average: number;
    /**
     * The date of this historical statistic entry
     */
    date: string;
    /**
     * highest number
     */
    highest: number;
    /**
     * lowest number
     */
    lowest: number;
    /**
     * Total number of orders happened that day
     */
    order_count: number;
    /**
     * Total
     */
    volume: number;
}

