/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetUniverseFactions200Ok { 
    /**
     * corporation_id integer
     */
    corporation_id?: number;
    /**
     * description string
     */
    description: string;
    /**
     * faction_id integer
     */
    faction_id: number;
    /**
     * is_unique boolean
     */
    is_unique: boolean;
    /**
     * militia_corporation_id integer
     */
    militia_corporation_id?: number;
    /**
     * name string
     */
    name: string;
    /**
     * size_factor number
     */
    size_factor: number;
    /**
     * solar_system_id integer
     */
    solar_system_id?: number;
    /**
     * station_count integer
     */
    station_count: number;
    /**
     * station_system_count integer
     */
    station_system_count: number;
}

