/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetUniverseSystemJumps200Ok { 
    /**
     * ship_jumps integer
     */
    ship_jumps: number;
    /**
     * system_id integer
     */
    system_id: number;
}

