/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetUniverseGraphicsGraphicIdOk { 
    /**
     * collision_file string
     */
    collision_file?: string;
    /**
     * graphic_file string
     */
    graphic_file?: string;
    /**
     * graphic_id integer
     */
    graphic_id: number;
    /**
     * icon_folder string
     */
    icon_folder?: string;
    /**
     * sof_dna string
     */
    sof_dna?: string;
    /**
     * sof_fation_name string
     */
    sof_fation_name?: string;
    /**
     * sof_hull_name string
     */
    sof_hull_name?: string;
    /**
     * sof_race_name string
     */
    sof_race_name?: string;
}

