/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetWarsWarIdAggressor } from './getWarsWarIdAggressor';
import { GetWarsWarIdAlly } from './getWarsWarIdAlly';
import { GetWarsWarIdDefender } from './getWarsWarIdDefender';


/**
 * 200 ok object
 */
export interface GetWarsWarIdOk { 
    aggressor: GetWarsWarIdAggressor;
    /**
     * allied corporations or alliances, each object contains either corporation_id or alliance_id
     */
    allies?: Array<GetWarsWarIdAlly>;
    /**
     * Time that the war was declared
     */
    declared: string;
    defender: GetWarsWarIdDefender;
    /**
     * Time the war ended and shooting was no longer allowed
     */
    finished?: string;
    /**
     * ID of the specified war
     */
    id: number;
    /**
     * Was the war declared mutual by both parties
     */
    mutual: boolean;
    /**
     * Is the war currently open for allies or not
     */
    open_for_allies: boolean;
    /**
     * Time the war was retracted but both sides could still shoot each other
     */
    retracted?: string;
    /**
     * Time when the war started and both sides could shoot each other
     */
    started?: string;
}

