/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostCharactersCharacterIdFittingsItem } from './postCharactersCharacterIdFittingsItem';


/**
 * fitting object
 */
export interface PostCharactersCharacterIdFittingsFitting { 
    /**
     * description string
     */
    description: string;
    /**
     * items array
     */
    items: Array<PostCharactersCharacterIdFittingsItem>;
    /**
     * name string
     */
    name: string;
    /**
     * ship_type_id integer
     */
    ship_type_id: number;
}

