/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface PostUniverseNames200Ok { 
    /**
     * category string
     */
    category: PostUniverseNames200Ok.CategoryEnum;
    /**
     * id integer
     */
    id: number;
    /**
     * name string
     */
    name: string;
}
export namespace PostUniverseNames200Ok {
    export type CategoryEnum = 'alliance' | 'character' | 'constellation' | 'corporation' | 'inventory_type' | 'region' | 'solar_system' | 'station' | 'faction';
    export const CategoryEnum = {
        Alliance: 'alliance' as CategoryEnum,
        Character: 'character' as CategoryEnum,
        Constellation: 'constellation' as CategoryEnum,
        Corporation: 'corporation' as CategoryEnum,
        InventoryType: 'inventory_type' as CategoryEnum,
        Region: 'region' as CategoryEnum,
        SolarSystem: 'solar_system' as CategoryEnum,
        Station: 'station' as CategoryEnum,
        Faction: 'faction' as CategoryEnum
    };
}


