/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 201 created object
 */
export interface PostFleetsFleetIdWingsWingIdSquadsCreated { 
    /**
     * The squad_id of the newly created squad
     */
    squad_id: number;
}

