/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostCharactersCharacterIdAssetsLocationsPosition } from './postCharactersCharacterIdAssetsLocationsPosition';


/**
 * 200 ok object
 */
export interface PostCharactersCharacterIdAssetsLocations200Ok { 
    /**
     * item_id integer
     */
    item_id: number;
    position: PostCharactersCharacterIdAssetsLocationsPosition;
}

