export enum NCVariant {
    FITTING_CONFIGURATION = '-FITTING-CONFIGURATION-',
    FITTING_LIST = '-FITTING-LIST-',
    KNOWN_SYSTEMS = '-KNOWN_SYSTEMS-',
    MANUFACTURE_RESEARCH = '-MANUFACTURE-RESEARCH-',
    AVAILABLE_BLUEPRINTS = '-AVAILABLE-BLUEPRINTS-'
}
