export enum NCVariant {
    DEFAULT='-DEFAULT-',
    FITTING_CONFIGURATION = '-FITTING-CONFIGURATION-',
    FITTING_LIST = '-FITTING-LIST-',
    KNOWN_SYSTEMS = '-KNOWN_SYSTEMS-',
    MANUFACTURE_RESEARCH = '-MANUFACTURE-RESEARCH-',
    AVAILABLE_BLUEPRINTS = '-AVAILABLE-BLUEPRINTS-',
    BLUEPRINT_BOM = '-BLUEPRINT-BOM-',
    SOLAR_SYSTEM_LOOKUP='-SOLAR-SYSTEM-LOOKUP-'
}
