server:
  port: 9500
P:
  runtime:
    configuration:
      properties:
        path: properties-dev
    filesystem:
      application:
        directory: ./NeoCom.Infinity.development
neocom:
  database:
    neocom:
      databasehost: "jdbc:postgresql://localhost:5432"
      databasepath: postgres
      databaseuser: neocom
      databasepassword: 01.Alpha
