server:
  port: 9500
P:
  runtime:
    configuration:
      properties:
        path: properties-dev
    filesystem:
      application:
        directory: ./NeoCom.Infinity.development
neocom:
  sde:
    database:
      schema: "jdbc:sqlite:"
      path: "backend.App/build/resources/main/"
      name: sde.db
