# - S E R V E R
server:
  port: ${PORT}

#  - D A T A B A S E
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: neocom
    password: 01.Alpha
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
P:
  runtime:
    configuration:
      properties:
        path: "/build/resources/main/properties"
    filesystem:
      application:
        directory: ./NeoCom.Infinity
    logging:
      request: false
      response: false
      timing: true
      metrics: true
    security:
      handlers:

neocom:
  sde:
    database:
      schema: "jdbc:sqlite:"
      path: "build/resources/main/"
      name: sde.db
