server:
  port: 9500
P:
  runtime:
    configuration:
      properties:
        path: "/build/resources/main/properties-dev"
    filesystem:
      application:
        directory: ./NeoCom.Infinity.development
