server:
  port: 9500
P:
  runtime:
    configuration:
      properties:
        path: "/build/resources/main/properties-dev"
    filesystem:
      application:
        directory: ./NeoCom.Infinity.development
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: neocom
    password: 01.Alpha
    driver-class-name: org.postgresql.Driver
