apiVersion: v1
kind: Service
metadata:
  name: nif-svc
  namespace: neocom
spec:
  selector:
    app: nif-stage
    version: 0.20.0-437
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 5203
      nodePort: 30000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nif-stage
  namespace: neocom
  labels:
    app: nif-stage
    version: 0.20.0-437
    module: neocom-infinity-frontend
spec:
  selector:
    matchLabels:
      app: nif-stage
  template:
    metadata:
      labels:
        app: nif-stage
        version: 0.20.0-437
        module: neocom-infinity-frontend
    spec:
      containers:
      - name: nif-stage
        image: adamantinoo/neocom-infinity-frontend:0.20.0-437
        env:
        - name: NODE_ENV
          value: "stage"
        ports:
        - containerPort: 5203
        imagePullPolicy: Always
      serviceAccountName: default
