apiVersion: v1
kind: Service
metadata:
  name: nif-svc
  namespace: neocom
spec:
  selector:
    app: nif-staging
    version: 0.20.0-455
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 5200
      nodePort: 32000

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: neocom-frontend-environment
  namespace: neocom
data:
  LOGIN_LINK: ""
  SEMVER: "0.20.0"
  TAGVERSION: "0.20.0-455"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nif-staging
  namespace: neocom
  labels:
    app: nif-staging
    version: 0.20.0-455
    module: neocom-infinity-frontend
spec:
  selector:
    matchLabels:
      app: nif-staging
  template:
    metadata:
      labels:
        app: nif-staging
        version: 0.20.0-455
        module: neocom-infinity-frontend
    spec:
      containers:
      - name: nif-staging
        image: adamantinoo/neocom-infinity-frontend:0.20.0-455
        env:
        - name: NODE_ENV
          value: "staging"
        - name: LOGIN_LINK # Notice that the case is different here
                                     # from the key name in the ConfigMap.
          valueFrom:
            configMapKeyRef:
              name: neocom-frontend-environment           # The ConfigMap this value comes from.
              key: LOGIN_LINK # The key to fetch.
        - name: SEMVER 
          valueFrom:
            configMapKeyRef:
              name: neocom-frontend-environment
              key: SEMVER
        - name: SEMVER 
          valueFrom:
            configMapKeyRef:
              name: neocom-frontend-environment
              key: SEMVER
        ports:
        - containerPort: 5200
        imagePullPolicy: Always
      serviceAccountName: default
