apiVersion: v1
kind: Service
metadata:
  name: $APP_CODE-$ENV-svc
  namespace: $NAMESPACE
spec:
  selector:
    app: $APP_CODE
    environment: $ENV
  type: NodePort
  ports:
    - nodePort: $EXPOSE_PORT
      protocol: TCP
      port: $PORT
      targetPort: $PORT     
status:
  loadBalancer: {}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: $APP_CODE-config
  namespace: $NAMESPACE
stringData:
  PORT: "$PORT"
  NEOCOM_DATABASE_URL: "$NEOCOM_DATABASE_URL"
  SPRING_DATASOURCE_URL: "$SPRING_DATASOURCE_URL"
  SPRING_DATASOURCE_USERNAME: "$SPRING_DATASOURCE_USERNAME"
  SPRING_DATASOURCE_PASSWORD: "$SPRING_DATASOURCE_PASSWORD"
  APPLICATION_DIRECTORY: "/app/NeoCom.Infinity.$ENVIRONMENT"
  NEOCOM_BANNER_LOCATION: "./resources/main/app-banner.txt"
  PROFILE: "$ENVIRONMENT"
  PROPERTIES_DIRECTORY: "/resources/main/properties-$ENVIRONMENT"
  REDIS_URL: "$REDIS_CACHE_URL"
  SDE_DATABASE_PATH: "/resources/main/sde.db"

---

apiVersion: v1
kind: Secret
metadata:
  name: $APP_CODE-secrets
  namespace: $NAMESPACE
data:
  SPRING_DATASOURCE_URL: $SPRING_DATASOURCE_URL
  SPRING_DATASOURCE_USERNAME: $SPRING_DATASOURCE_USERNAME
  SPRING_DATASOURCE_PASSWORD: $SPRING_DATASOURCE_PASSWORD
  NEOCOM_DATABASE_URL: $NEOCOM_DATABASE_URL

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_CODE
  namespace: $NAMESPACE
  labels:
    app: $APP_CODE
    version: "$VERSION"
    port: "$PORT"
spec:
  selector:
    matchLabels:
      app: $APP_CODE
      environment: $ENV
  template:
    metadata:
      labels:
        app: $APP_CODE-$ENV
        environment: $ENV
        version: "$VERSION"
        port: "$PORT"
        module: $MODULE_NAME
    spec:
      containers:
        - name: $APP_CODE
          image: adamantinoo/$IMAGE_TAG
          env:
            - name: NODE_ENV
              value: $ENV
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: $APP_CODE-secrets
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: $APP_CODE-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: PROPERTIES_DIRECTORY
              valueFrom:
                configMapKeyRef:
                  name: $APP_CODE-config
                  key: PROPERTIES_DIRECTORY

          ports:
            - containerPort: $PORT
          imagePullPolicy: Always
      serviceAccountName: default
