apiVersion: v1
kind: Service
metadata:
  name: neocom-$APP_CODE-svc
  namespace: $NAMESPACE
spec:
  selector:
    app: $APP_CODE-$ENV
    version: $VERSION
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: $PORT
      nodePort: 32000

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: neocom-frontend-environment
  namespace: $NAMESPACE
data:
  NODE_ENV: "$NODE_ENV"
  PORT: "$PORT"
  ENVIRONMENT: "$ENVIRONMENT"
  NODE_VERSION: "$NODE_VERSION"
  PRODUCTION: $PRODUCTION
  SEMVERSION: "$SEMVERSION"
  VERSION: "$VERSION"
  ESI_CLIENTID: "$ESI_CLIENTID"
  ESI_STATE: "$ESI_STATE"
  CALLBACK_URL: "$CALLBACK_URL"
  ESIPROXY: "$ESIPROXY"
  OAUTHPROXY: "$OAUTHPROXY"
  PUBLICPROXY: "$PUBLICPROXY"
  BACKENDPROXY: "$BACKENDPROXY"
  NESTPROXY: "$NESTPROXY"
  APP_CODE: "$APP_CODE"
  MODULE_NAME: "$MODULE_NAME"
  APP_HOME: "$APP_HOME"
  APP_BASEREF: "$APP_BASEREF"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_CODE-$ENV
  namespace: $NAMESPACE
  labels:
    app: $APP_CODE-$ENV
    version: "$VERSION"
    port: "$PORT"
    module: $MODULE_NAME
spec:
  selector:
    matchLabels:
      app: $APP_CODE-$ENV
  template:
    metadata:
      labels:
        app: $APP_CODE-$ENV
        version: "$VERSION"
        port: "$PORT"
        module: $MODULE_NAME
    spec:
      containers:
      - name: $APP_CODE-$ENV
        image: adamantinoo/$IMAGE_TAG
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: neocom-frontend-environment
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: neocom-frontend-environment
              key: PORT
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: neocom-frontend-environment
              key: ENVIRONMENT
        - name: NODE_VERSION
          valueFrom:
            configMapKeyRef:
              name: neocom-frontend-environment
              key: NODE_VERSION
        - name: PRODUCTION
          valueFrom:
            configMapKeyRef:
              name: neocom-frontend-environment
              key: PRODUCTION
        - name: SEMVERSION
          valueFrom:
            configMapKeyRef:
              name: neocom-frontend-environment
              key: SEMVERSION
        - name: VERSION
          valueFrom:
            configMapKeyRef:
              name: neocom-frontend-environment
              key: VERSION
        - name: ESI_CLIENTID
          valueFrom:
            configMapKeyRef:
              name: neocom-frontend-environment
              key: ESI_CLIENTID
        - name: ESI_STATE
          valueFrom:
            configMapKeyRef:
              name: neocom-frontend-environment
              key: ESI_STATE
        - name: CALLBACK_URL
          valueFrom:
            configMapKeyRef:
              name: neocom-frontend-environment
              key: CALLBACK_URL
        - name: ESIPROXY
          valueFrom:
            configMapKeyRef:
              name: neocom-frontend-environment
              key: ESIPROXY
        - name: OAUTHPROXY
          valueFrom:
            configMapKeyRef:
              name: neocom-frontend-environment
              key: OAUTHPROXY
        - name: PUBLICPROXY
          valueFrom:
            configMapKeyRef:
              name: neocom-frontend-environment
              key: PUBLICPROXY
        - name: BACKENDPROXY
          valueFrom:
            configMapKeyRef:
              name: neocom-frontend-environment
              key: BACKENDPROXY
        - name: NESTPROXY
          valueFrom:
            configMapKeyRef:
              name: neocom-frontend-environment
              key: NESTPROXY
        - name: APP_CODE
          valueFrom:
            configMapKeyRef:
              name: neocom-frontend-environment
              key: APP_CODE
        - name: MODULE_NAME
          valueFrom:
            configMapKeyRef:
              name: neocom-frontend-environment
              key: MODULE_NAME
        - name: APP_HOME
          valueFrom:
            configMapKeyRef:
              name: neocom-frontend-environment
              key: APP_HOME
        - name: APP_BASEREF
          valueFrom:
            configMapKeyRef:
              name: neocom-frontend-environment
              key: APP_BASEREF
        ports:
        - containerPort: $PORT
        imagePullPolicy: Always
      serviceAccountName: default
