swagger: '2.0'
info:
  title: NeoCom Backend API
  version: 0.27
basePath: /
tags:
  - name: Authorization
    description: NeoCom Authorization Endpoint set
paths:
  '/api/v1/neocom/refreshAuthorization':
    get:
      tags:
        - Authorization
      summary: Validated if the front end application is still authenticated with a valit token.
      description: |
        The front end sens a http only cookie with the current token if exists. In case there is no cookie, the token is invalid or the credential
        pointed by the token is not found then the endpoint retuns a message to start the login process.
        If the cookie exists, the JWT token is valid and the Credential is found then the cookie y time extended and the application continues to
        the Dashboard page.
      operationId: refreshAuthorizationToken
      responses:
        '200':
          description: Validation completed successfully and the authentication state is ready.
          content:
            'application/json;charset=UTF-8':
              schema:
                $ref: '#/components/schemas/AuthenticationStateResponse'

