apiVersion: v1
kind: Service
metadata:
  name: $APP_CODE-svc
  namespace: $NAMESPACE
spec:
  selector:
    app: $APP_CODE
    environment: $ENV
  type: NodePort
  ports:
    - nodePort: $EXPOSE_PORT
      protocol: TCP
      port: $PORT
      targetPort: $PORT     
status:
  loadBalancer: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_CODE
  namespace: $NAMESPACE
  labels:
    app: $APP_CODE
    environment: $ENV
spec:
  selector:
    matchLabels:
      app: $APP_CODE
      environment: $ENV
  template:
    metadata:
      labels:
        app: $APP_CODE
        environment: $ENV
        version: "$VERSION"
        port: "$PORT"
        module: $MODULE_NAME
    spec:
      containers:
      - name: $APP_CODE
        image: adamantinoo/$IMAGE_TAG
        env:
        - name: NODE_ENV
          value: $ENV
        ports:
        - containerPort: $PORT
        imagePullPolicy: Always
      serviceAccountName: default
