FROM node:20-alpine

ENV NODE_ENV=$ENV

COPY ./node_modules /app/node_modules
COPY ./dist /app/dist
COPY package.json /app
COPY .app-banner.txt /app
COPY .env* /app

WORKDIR /app

# Expose the port on which the app will run
EXPOSE $PORT
# Start the server using the production build
CMD ["node", "dist/main"]
