apiVersion: v1
kind: Service
metadata:
  name: $PROJECT_CODE-svc
  namespace: neocom
spec:
  selector:
    app: $PROJECT_CODE-$ENV
    version: $VERSION
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: $PORT
      nodePort: 33000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: $PROJECT_CODE-$ENV
  namespace: neocom
  labels:
    app: $PROJECT_CODE-$ENV
    version: $VERSION
    module: neocom-infinity-backend
spec:
  selector:
    matchLabels:
      app: $PROJECT_CODE-$ENV
  template:
    metadata:
      labels:
        app: $PROJECT_CODE-$ENV
        version: $VERSION
        module: neocom-infinity-backend
    spec:
      containers:
      - name: $PROJECT_CODE-$ENV
        image: adamantinoo/$IMAGE_NAME:$VERSION
        ports:
        - containerPort: $PORT
        imagePullPolicy: Always
      serviceAccountName: default
