# FRONTEND - Docker Composer components
# PROJECT CODE - 52
#
# Docker composer automatically creates a network. The container host matches the container name. To differentiate and create single networks use a directory name that should be unique. The recommended format is: <project>-docker-<environment>
# The frontend requires some api simutators to mock most of the call but call to already implemented and inmutable endpotins should be routed directly to docker services just created for the front end environment.
#
# The routing references are:
# /api/v1/universe - this calls inmutable endpoints so it can use a local backend implementation or the stage production implementation once it is deployed.
# /api/v1/public - can be mocked to return predefined and repeteable responses.
# /api - mocked to canned responses

version: '3.8'

services:
  neocom-frontend-development-backend-apisimulator:
    container_name: neocom-frontend-development-backend-apisimulator
    image: apimastery/apisimulator:1.8
    ports:
      - "5210:6090"
    volumes:
      # WARNING - Use full absolute paths to make this work.
      - /home/adam/Development/NeoCom0.20/NeoCom-Infinity/NeoCom-Infinity-Frontend/support/backend-simulation:/backend-simulation
    command: "bin/apisimulator start /backend-simulation -p 6090"

  neocom-frontend-development-public-apisimulator:
    container_name: neocom-frontend-development-public-apisimulator
    image: apimastery/apisimulator:1.8
    ports:
      - "5290:6090"
    volumes:
      # WARNING - Use full absolute paths to make this work.
      - /home/adam/Development/NeoCom0.20/NeoCom-Infinity/NeoCom-Infinity-Frontend/support/public-simulation:/public-simulation
    command: "bin/apisimulator start /public-simulation -p 6090"

  # neocom-frontend-development-backend-app:
  #   container_name: neocom-frontend-development-backend-app
  #   image: neocom/neocom-infinity.backend
  #   ports:
  #     - "5220:9500"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=dev
  #     - PROFILE=development
  #     - JDBC_DATABASE_URL=jdbc:postgresql://neocom-frontend-development-postgres:5432/postgres
  #     - DB_USER=neocom-user
  #     - DB_PASSWORD=neocom-password
  #     - NEOCOM_DATABASE_URL=jdbc:postgresql://neocom-frontend-development-postgres:5432/postgres?user=neocom-user&password=neocom-password
  #     - DEFAULT_BACKEND_SERVER="http://localhost:"
  #     - NEOCOM_BANNER_LOCATION=./app-banner.txt
  #     - PROPERTIES_DIRECTORY=/properties-dev
  #     - APPLICATION_DIRECTORY=./NeoCom.Infinity.Development
  #     - SDE_DATABASE_PATH=./sde.db

  # neocom-frontend-development-postgres:
  #   container_name: neocom-frontend-development-postgres
  #   image: "postgres:11.2"
  #   ports:
  #     - "5230:5432"
  #   environment:
  #     - CURRENT_UID=1000
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=neocom-user
  #     - POSTGRES_PASSWORD=neocom-password
