version: '3'
services:
  postgres:
    image: "postgres:11.2"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=neocom
      - POSTGRES_PASSWORD=01.Alpha
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data