apiVersion: v1
kind: Service
metadata:
  name: neocom-$APP_CODE-svc
  namespace: $NAMESPACE
spec:
  selector:
    app: $APP_CODE-$ENV
    version: $VERSION
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: $PORT
      nodePort: 32009

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_CODE-$ENV
  namespace: $NAMESPACE
  labels:
    app: $APP_CODE-$ENV
    version: "$VERSION"
    port: "$PORT"
    module: $APP_CODE
spec:
  selector:
    matchLabels:
      app: $APP_CODE-$ENV
  template:
    metadata:
      labels:
        app: $APP_CODE-$ENV
        version: "$VERSION"
        port: "$PORT"
        module: $APP_CODE
    spec:
      containers:
      - name: $APP_CODE-$ENV
        image: adamantinoo/neocom-poc:$VERSION
        envFrom:
          - configMapRef:
              name: neocom-poc-environment
        ports:
        - containerPort: $PORT
        imagePullPolicy: Always
      serviceAccountName: default
