spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master-dev.yaml

P:
  runtime:
    filesystem:
      application:
        directory: "./build/neocom-cache/NeoCom.Infinity.Development"
    logging:
      request: true
      response: true
      timing: true
      metrics: true
