server:
  port: 9500

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true
  info:
    id: info
    sensitive: false
    enabled: true

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
